import type { Level } from '@/types';

export const level37Realtime: Level = {
	id: 'act5-level37-realtime',
	actId: 5,
	levelNumber: 37,
	name: 'Real-Time',
	requiresTests: true,
	trigger: {
		type: 'new_feature',
		description:
			'Users want live notifications when their payments complete. The ProcessPayment service has no way to push updates. HTTP polling every 2 seconds is killing the server with 50,000 concurrent users.',
	},
	startingPipeline: {
		nodes: [],
		connections: [],
	},
	problem: {
		observation:
			'50,000 users polling every 2 seconds = 25,000 requests/second. 99% of polls return empty. Server CPU at 95%. The ProcessPayment service creates records but has no real-time push mechanism.',
		rootCause:
			'HTTP polling wastes resources when there are no new events. Need server-push via WebSockets to only send data when something actually changes.',
		codeExample: `# The ProcessPayment service completes payments,
# but has no way to notify users in real-time.
# Clients must poll GET /notifications every 2 seconds.
#
# 50K users x 0.5 req/sec = 25K wasted requests/sec
# 99% return empty arrays. CPU at 95%.
#
# app/services/process_payment.rb
class ProcessPayment < ApplicationService
  Result = Data.define(:success?, :payment, :errors)

  def call
    validation = PaymentContract.new.call(@params)
    return failure(validation) if validation.failure?

    payment = @user.payments.create!(amount: @params[:amount])
    # No way to tell the user their payment completed!
    # They find out on their next poll cycle (up to 2s delay)
    Result.new(success?: true, payment:, errors: {})
  end
end`,
		goal: 'Replace HTTP polling with WebSocket push for real-time notifications, authenticate connections, and build a broadcast service.',
		thresholds: {},
	},
	successConditions: [],
	availableNodes: [],
	unlockedNodes: [],
	learningContent: {
		title: 'Real-Time with Action Cable & Solid Cable',
		goal: `In this level, you'll:\n- Replace HTTP polling with WebSocket push for real-time notifications\n- Install a database-backed WebSocket adapter (no Redis required)\n- Authenticate WebSocket connections via encrypted cookies\n- Build a broadcast service that pushes updates when records are created`,
		conceptExplanation: `Action Cable integrates WebSockets with Rails. Rails 8 uses Solid Cable as the default adapter, storing pub/sub messages in the database instead of Redis.

**Solid Cable (Rails 8 default):**
- Uses the database for pub/sub instead of Redis
- No additional infrastructure needed
- Handles most apps (< 100K concurrent connections)
- Automatic message pruning via configurable retention

**Action Cable concepts:**
- **Channel**: Like a controller for WebSockets (subscribe/unsubscribe/receive)
- **Stream**: A named broadcast target (e.g., "notifications:user_42")
- **Connection**: The WebSocket connection with authentication
- **Subscription**: Client subscribes to a channel to receive pushes

**Token authentication for SPA / mobile clients:**
The example above uses encrypted cookies, which is exactly what the Rails 8 \`bin/rails generate authentication\` generator produces. The generated \`ApplicationCable::Connection\` looks up the session by id stored in a signed cookie:

\`\`\`ruby
# Generated by bin/rails generate authentication
# (rails/rails: railties/lib/rails/generators/rails/authentication/templates/
#  app/channels/application_cable/connection.rb.tt)
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      set_current_user || reject_unauthorized_connection
    end

    private

    def set_current_user
      if session = Session.find_by(id: cookies.signed[:session_id])
        self.current_user = session.user
      end
    end
  end
end
\`\`\`

**Cross-origin SPA / mobile clients:** Cookies are sent automatically by the browser when the SPA is on the same origin (or properly configured with \`credentials: 'include'\` and a cookie-allowing CORS policy). For a true cross-origin SPA or a mobile client where cookies are not viable, the Rails 8 default authentication generator does NOT ship a bearer-token flow out of the box. Three options, in increasing complexity:

1. **Same-origin deploy** (Rails app and SPA share a hostname). Use the generated cookie-based flow as-is.
2. **CORS + credentials**. Configure \`Rack::Cors\` to allow the SPA origin with credentials, and set the SPA's \`fetch\` / WebSocket constructor to send cookies. Still uses the generated session lookup unchanged.
3. **Custom token column**. Add a \`token\` column to the \`Session\` model, expose a sign-in endpoint that returns the token, and replace the cable connection's lookup with \`Session.find_by(token: request.params[:token])\`. This is custom work; document it in your codebase so future readers do not assume Rails ships it.

Logout invalidation: when the user signs out, the controller deletes the \`Session\` row. New WebSocket subscribe attempts fail because the lookup returns nil. Existing connections do not auto-tear-down; emit a "logout" event on a user-scoped channel and have the client disconnect on receipt.

**Broadcast IDs, not full payloads:**
The example serializes the full notification into the broadcast. At a few hundred concurrent subscribers per stream this is fine; past that, it doubles the database write (audit log of broadcast bytes) and bloats the WebSocket frame. The production-safe default is to broadcast a tiny payload with the id, and let the client fetch the detail:

\`\`\`ruby
NotificationsChannel.broadcast_to(user, { type: "notification.created", id: notification.id })
# Client receives event, calls GET /api/notifications/<id> over the cached HTTP path
\`\`\`
This also keeps WebSocket and HTTP semantics aligned: the source of truth lives at the GET endpoint, the WebSocket is a notification of "go fetch this." Cache hits on the HTTP side absorb most of the load.

You may have learned in an earlier level that side effects do not belong in model callbacks. Broadcasting a record's creation is the recognized exception: it is a pure derived notification of a committed state change (it fires only after_commit, it is idempotent, and it is the same for every caller), which is why Rails' own Turbo and broadcasts_to helpers are built on after_commit.

**Per-user rate limiting on subscribe:**
Each WebSocket subscription opens a server-side resource. A malicious client can subscribe to thousands of channels in a loop. Add a Rack::Attack-style throttle on the subscribe action:

\`\`\`ruby
class NotificationsChannel < ApplicationCable::Channel
  SUBSCRIBE_LIMIT = 5
  SUBSCRIBE_WINDOW = 1.minute

  def subscribed
    key = "subscribes:#{current_user.id}"
    count = Rails.cache.increment(key, 1, expires_in: SUBSCRIBE_WINDOW)
    return reject if count > SUBSCRIBE_LIMIT
    stream_for current_user
  end
end
\`\`\`
The connection-level rate limit on the underlying WebSocket is separate (handled by the proxy / Rack::Attack); this limits the per-channel subscribe rate.

**Solid Cable retention tradeoffs:**
\`message_retention: 1.day\` (the example) is purely a database-cleanup cutoff: how long a row lives in the \`solid_cable_messages\` table before Solid Cable autotrims it. Per the Solid Cable README, messages are autotrimmed based on the \`message_retention\` setting, and the trim runs when a message is broadcast (https://github.com/rails/solid_cable). It is NOT a replay buffer. Action Cable never replays messages to a client that was disconnected, regardless of retention: a larger retention window only means the messages table holds more rows (more database cost) before trimming, it does not hand a late subscriber a backlog.

So pick retention based on broadcast volume and database cost, not on missed-message recovery. For a high-volume notification system, drop retention to 1 hour or even 5 minutes so the table stays small and the trim keeps up. For low-volume apps, 1 day is fine. A reconnecting client recovers missed state by re-fetching from the HTTP API (see below), never from the WebSocket.

**When to graduate from Solid Cable:**
Solid Cable scales to roughly tens of thousands of concurrent connections per Rails process before the polling adapter (default \`polling_interval: 0.1\` seconds) becomes the bottleneck. Past that, the graduation path is:

1. **AnyCable** (Go-based WebSocket server, drop-in replacement) for hundreds of thousands of concurrent connections.
2. **A separate WebSocket service** (Phoenix Channels, a Node service) when the team is willing to maintain a non-Rails component.

For a Rails 8 app under "billion-dollar SaaS" load profile, Solid Cable handles the realtime tier of most products without that graduation. The decision is volume-driven; do not graduate prematurely.

**Reconnection and message ordering:**
Messages broadcast while a client is disconnected are simply lost. Action Cable has no backlog, and Solid Cable's retention is a cleanup cutoff, not a replay buffer, so a reconnecting client never receives what it missed. The correct pattern is: on reconnect, the client re-fetches current state from the HTTP API (the source of truth), then resumes listening for live pushes.

For ordering-sensitive flows (chat, audit log), the live messages a client DOES receive can still arrive slightly out of order, so include a server-side sequence number in each broadcast and let the client order and de-duplicate:

\`\`\`ruby
{ type: "message.created", id: msg.id, seq: msg.id, at: msg.created_at.iso8601(6) }
\`\`\`
\`seq\` (use the model id, monotonic by definition) lets the client drop duplicates and order the small window of live messages it receives.`,
		railsCodeExample: `# config/cable.yml (Solid Cable, no Redis!)
production:
  adapter: solid_cable
  polling_interval: 0.1.seconds
  message_retention: 1.day

# app/channels/application_cable/connection.rb
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      self.current_user = find_verified_user
    end

    private

    def find_verified_user
      if session = Session.find_by(id: cookies.signed[:session_id])
        session.user
      else
        reject_unauthorized_connection
      end
    end
  end
end

# app/channels/notifications_channel.rb
class NotificationsChannel < ApplicationCable::Channel
  def subscribed
    stream_for current_user
  end
end

# app/services/broadcast_notification.rb
class BroadcastNotification < ApplicationService
  Result = Data.define(:success?, :notification, :errors)

  def initialize(user:, title:, body:)
    @user = user
    @title = title
    @body = body
  end

  def call
    validation = NotificationContract.new.call(
      title: @title, body: @body
    )
    if validation.failure?
      return Result.new(
        success?: false, notification: nil,
        errors: validation.errors.to_h
      )
    end

    notification = @user.notifications.create!(
      title: @title, body: @body
    )
    # after_create_commit on Notification broadcasts automatically
    Result.new(success?: true, notification:, errors: {})
  end
end

# app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  validates :title, :body, presence: true

  after_create_commit :broadcast_to_user

  private

  def broadcast_to_user
    NotificationsChannel.broadcast_to(
      user,
      NotificationSerializer.new(self).serializable_hash
    )
  end
end`,
		commonMistakes: [
			'Not authenticating WebSocket connections (anyone can subscribe)',
			'Broadcasting too much data (send IDs, let client fetch details)',
			'Using Redis when Solid Cable is sufficient (unnecessary infrastructure)',
			'Broadcasting in the request cycle instead of via model callbacks',
			'Cookie-based Connection auth on a SPA / mobile client (cookies are not always sent on cross-origin WebSocket upgrades, and browsers cannot set custom headers on the WebSocket handshake). Pass a signed session token as a query parameter on the wss:// URL instead',
			'Logout that invalidates the session but leaves the WebSocket open (the client keeps receiving private events). Emit a logout event on the user channel and force the client to disconnect',
			'No per-user subscribe rate limit (a malicious client opens thousands of channels in a loop)',
			'message_retention: 1.day on a high-volume broadcaster (every broadcast writes a row; the retention table grows faster than cleanup can prune it). Pick a retention window the cleanup job can actually keep up with',
			'Assuming WebSocket delivery is ordered across reconnects. Include a sequence number in every broadcast for ordering-sensitive flows',
		],
		whenToUse:
			'Live notifications, chat, real-time dashboards, collaborative editing. Replace polling whenever events are infrequent relative to poll interval.',
		furtherReading: [
			{
				title: 'Action Cable Overview',
				url: 'https://guides.rubyonrails.org/action_cable_overview.html',
			},
			{
				title: 'Solid Cable (Rails 8)',
				url: 'https://github.com/rails/solid_cable',
			},
			{
				title: 'AnyCable (Go-based WebSocket server)',
				url: 'https://anycable.io/',
			},
		],
		homework: [
			{
				task: 'Install Solid Cable, point development at it in config/cable.yml (adapter: solid_cable), and create its table.',
				commands: [
					'bundle add solid_cable',
					'bin/rails solid_cable:install',
					'bin/rails db:prepare',
				],
				verify:
					'config/cable.yml uses the solid_cable adapter and the solid_cable_messages table exists. No Redis anywhere.',
			},
			{
				task: 'Generate a Notifications channel and have subscribed call stream_for current_user.',
				commands: ['bin/rails generate channel Notifications'],
				verify:
					'app/channels/notifications_channel.rb exists alongside app/channels/application_cable/connection.rb, where connections are authenticated.',
			},
			{
				task: 'Broadcast from the console and watch the message land in the database-backed pub/sub bus.',
				commands: [
					'bin/rails console',
					'NotificationsChannel.broadcast_to(User.first, { type: "notification.created", id: 1 })',
					'SolidCable::Message.count',
				],
				verify:
					'Each broadcast writes a row into solid_cable_messages (the count goes up): that table is the pub/sub bus that replaces Redis for Action Cable.',
			},
		],
	},
	hint: {
		delay: 25,
		text: 'Three layers: the WebSocket adapter Rails 8 ships by default (no Redis needed), a channel class on top of it that handles per-user subscriptions, and a path from your business logic that pushes events to the channel when a domain change happens.',
	},
};
