import type { Realm, Challenge } from '../types';

// Realm definitions
export const realms: Realm[] = [
  { id: 'foundation', name: 'Foundation Fortress', description: 'Master the basics of Ruby on Rails', order: 1, dungeons: ['mvc', 'directory', 'routing-basics', 'controllers-101', 'views-erb'] },
  { id: 'activerecord', name: 'ActiveRecord Depths', description: 'Dive deep into models and database interactions', order: 2, dungeons: ['models', 'associations', 'validations', 'callbacks', 'queries'], unlockRequirement: { realm: 'foundation' } },
  { id: 'routing', name: 'Routing Labyrinth', description: 'Navigate the paths of Rails routing', order: 3, dungeons: ['restful', 'nested', 'custom', 'constraints', 'url-helpers'], unlockRequirement: { realm: 'activerecord' } },
  { id: 'controllers', name: 'Controller Citadel', description: 'Command and control your application', order: 4, dungeons: ['actions', 'params', 'rendering', 'flash', 'sessions'], unlockRequirement: { realm: 'routing' } },
  { id: 'views', name: 'View Valley', description: 'Craft beautiful user interfaces', order: 5, dungeons: ['layouts', 'helpers', 'forms', 'assets', 'turbo'], unlockRequirement: { realm: 'controllers' } },
  { id: 'database', name: 'Database Dungeons', description: 'Optimize your data layer', order: 6, dungeons: ['optimization', 'n-plus-one', 'indexing', 'arel', 'patterns'], unlockRequirement: { realm: 'views', level: 15 } },
  { id: 'performance', name: 'Performance Peaks', description: 'Scale to new heights with caching and background jobs', order: 7, dungeons: ['sidekiq', 'redis', 'caching', 'http-cache', 'job-optimization'], unlockRequirement: { realm: 'database', level: 25 } },
  { id: 'email', name: 'Email & Notifications', description: 'Master Action Mailer and notifications', order: 8, dungeons: ['mailer-setup', 'templates', 'async', 'testing', 'inbound'], unlockRequirement: { realm: 'performance', level: 35 } },
  { id: 'db-mastery', name: 'Database Mastery', description: 'Expert-level database techniques', order: 9, dungeons: ['explain', 'sharding', 'replicas', 'pooling', 'postgres'], unlockRequirement: { realm: 'email', level: 45 } },
  { id: 'devops', name: 'DevOps & Deployment', description: 'Deploy and operate Rails in production', order: 10, dungeons: ['capistrano', 'docker', 'cicd', 'monitoring', 'security'], unlockRequirement: { realm: 'db-mastery', level: 55 } },
  { id: 'architecture', name: 'Architecture Apex', description: 'Design patterns and scaling strategies', order: 11, dungeons: ['service-objects', 'cqrs', 'api-design', 'webhooks', 'multi-tenancy'], unlockRequirement: { realm: 'devops', level: 70 } },
];

// Dungeon metadata
export const dungeonMeta: Record<string, { name: string; description: string }> = {
  'mvc': { name: 'MVC Architecture', description: 'Understand the Model-View-Controller pattern' },
  'directory': { name: 'Directory Structure', description: 'Navigate the Rails folder structure' },
  'routing-basics': { name: 'Basic Routing', description: 'Learn how URLs map to actions' },
  'controllers-101': { name: 'Controllers 101', description: 'Master controller basics' },
  'views-erb': { name: 'Views & ERB', description: 'Create dynamic HTML templates' },
  'models': { name: 'Models & Migrations', description: 'Create and manage database tables' },
  'associations': { name: 'Associations', description: 'Connect models with relationships' },
  'validations': { name: 'Validations', description: 'Ensure data integrity' },
  'callbacks': { name: 'Callbacks', description: 'Hook into the ActiveRecord lifecycle' },
  'queries': { name: 'Query Interface', description: 'Master ActiveRecord queries' },
  'restful': { name: 'RESTful Routes', description: 'Master the seven resource routes' },
  'nested': { name: 'Nested Resources', description: 'Route parent-child relationships' },
  'custom': { name: 'Custom Routes', description: 'Create non-RESTful routes' },
  'constraints': { name: 'Route Constraints', description: 'Control route matching' },
  'url-helpers': { name: 'URL Helpers', description: 'Generate paths and URLs' },
};

// Map dungeon IDs to challenge ID prefixes
const dungeonToPrefix: Record<string, string> = {
  'mvc': 'foundation-mvc',
  'directory': 'foundation-directory',
  'routing-basics': 'foundation-routing',
  'controllers-101': 'foundation-controllers',
  'views-erb': 'foundation-views',
  'models': 'activerecord-models',
  'associations': 'activerecord-associations',
  'validations': 'activerecord-validations',
  'callbacks': 'activerecord-callbacks',
  'queries': 'activerecord-queries',
  'restful': 'routing-restful',
  'nested': 'routing-nested',
  'custom': 'routing-custom',
  'constraints': 'routing-constraints',
  'url-helpers': 'routing-helpers',
};

// All 150 challenges for 3 realms (Foundation, ActiveRecord, Routing)
const allChallenges: Challenge[] = [
  // === FOUNDATION - MVC (10) ===
  { id: 'foundation-mvc-001', type: 'multiple_choice', difficulty: 1, xp_reward: 20, monster: { name: 'Confused Controller', sprite: 'confused-controller', hp: 40 }, question: 'In the MVC pattern, which component is responsible for handling user input?', options: [{ id: 'a', text: 'Controller' }, { id: 'b', text: 'Model' }, { id: 'c', text: 'View' }, { id: 'd', text: 'Router' }], correct_answer: 'a', explanation: 'The Controller receives user input and coordinates between Model and View.' },
  { id: 'foundation-mvc-002', type: 'multiple_choice', difficulty: 1, xp_reward: 20, monster: { name: 'Model Muddle', sprite: 'model-muddle', hp: 40 }, question: 'Where should business logic primarily live in Rails?', options: [{ id: 'a', text: 'Controller' }, { id: 'b', text: 'Model' }, { id: 'c', text: 'View' }, { id: 'd', text: 'Routes' }], correct_answer: 'b', explanation: 'The Model is the proper place for business logic. Controllers should be thin.' },
  { id: 'foundation-mvc-003', type: 'multiple_choice', difficulty: 1, xp_reward: 20, monster: { name: 'View Vampire', sprite: 'view-vampire', hp: 45 }, question: 'What is the primary responsibility of the View?', options: [{ id: 'a', text: 'Processing input' }, { id: 'b', text: 'Storing data' }, { id: 'c', text: 'Presenting data to user' }, { id: 'd', text: 'Defining routes' }], correct_answer: 'c', explanation: 'The View is responsible for presentation - rendering data as HTML.' },
  { id: 'foundation-mvc-004', type: 'multiple_choice', difficulty: 1, xp_reward: 25, monster: { name: 'Fat Controller', sprite: 'fat-controller', hp: 50 }, question: 'What does "Fat Model, Skinny Controller" mean?', options: [{ id: 'a', text: 'Models should have many attributes' }, { id: 'b', text: 'Business logic in models, controllers minimal' }, { id: 'c', text: 'Models should be large files' }, { id: 'd', text: 'Use more models than controllers' }], correct_answer: 'b', explanation: 'Business logic should live in models while controllers coordinate.' },
  { id: 'foundation-mvc-005', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Request Wraith', sprite: 'request-wraith', hp: 55 }, question: 'In a Rails request cycle, what is the correct order?', options: [{ id: 'a', text: 'Router -> Controller -> Model -> View' }, { id: 'b', text: 'Controller -> Router -> View -> Model' }, { id: 'c', text: 'Model -> Controller -> Router -> View' }, { id: 'd', text: 'View -> Controller -> Model -> Router' }], correct_answer: 'a', explanation: 'Request hits Router, then Controller, which uses Model, then renders View.' },
  { id: 'foundation-mvc-006', type: 'fill_in_blank', difficulty: 2, xp_reward: 30, monster: { name: 'Naming Nightmare', sprite: 'naming-nightmare', hp: 55 }, question: 'If your model is named "Article", the controller should be:', code_snippet: 'class ____Controller < ApplicationController', correct_answer: 'Articles', explanation: 'Controllers are pluralized: Article model -> ArticlesController.' },
  { id: 'foundation-mvc-007', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Convention Crusher', sprite: 'convention-crusher', hp: 60 }, question: 'Which file contains HTML for displaying a list of users?', options: [{ id: 'a', text: 'app/controllers/users_controller.rb' }, { id: 'b', text: 'app/models/user.rb' }, { id: 'c', text: 'app/views/users/index.html.erb' }, { id: 'd', text: 'config/routes.rb' }], correct_answer: 'c', explanation: 'Views live in app/views, organized by controller name.' },
  { id: 'foundation-mvc-008', type: 'multiple_choice', difficulty: 2, xp_reward: 35, monster: { name: 'Inheritance Imp', sprite: 'inheritance-imp', hp: 60 }, question: 'What class do Rails controllers inherit from by default?', options: [{ id: 'a', text: 'ActionController::Base' }, { id: 'b', text: 'ApplicationController' }, { id: 'c', text: 'BaseController' }, { id: 'd', text: 'Rails::Controller' }], correct_answer: 'b', explanation: 'Controllers inherit from ApplicationController, which inherits from ActionController::Base.' },
  { id: 'foundation-mvc-009', type: 'code_analysis', difficulty: 3, xp_reward: 40, monster: { name: 'Logic Leech', sprite: 'logic-leech', hp: 70 }, question: 'What is wrong with this controller code?', code_snippet: 'def index\n  @articles = Article.where(published: true).order(views: :desc)\n  @articles.each { |a| a.view_count += 1; a.save }\nend', options: [{ id: 'a', text: 'Query is too complex' }, { id: 'b', text: 'Business logic in controller' }, { id: 'c', text: 'Both A and B - controller is too fat' }, { id: 'd', text: 'Nothing wrong' }], correct_answer: 'c', explanation: 'Controller has too much logic. Query should be a scope, view count update in Model.' },
  { id: 'foundation-mvc-010', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'MVC Master (BOSS)', sprite: 'mvc-boss', hp: 100 }, question: 'Which Rails principle complements MVC by reducing configuration?', options: [{ id: 'a', text: 'DRY' }, { id: 'b', text: 'Convention over Configuration' }, { id: 'c', text: 'Separation of Concerns' }, { id: 'd', text: 'Single Responsibility' }], correct_answer: 'b', explanation: 'Convention over Configuration means Rails assumes sensible defaults.' },

  // === FOUNDATION - DIRECTORY (10) ===
  { id: 'foundation-directory-001', type: 'multiple_choice', difficulty: 1, xp_reward: 20, monster: { name: 'Folder Fiend', sprite: 'folder-fiend', hp: 40 }, question: 'Where are Rails models stored by default?', options: [{ id: 'a', text: 'app/models/' }, { id: 'b', text: 'models/' }, { id: 'c', text: 'lib/models/' }, { id: 'd', text: 'db/models/' }], correct_answer: 'a', explanation: 'Rails models live in app/models/.' },
  { id: 'foundation-directory-002', type: 'multiple_choice', difficulty: 1, xp_reward: 20, monster: { name: 'Config Creature', sprite: 'config-creature', hp: 40 }, question: 'Which file contains database configuration?', options: [{ id: 'a', text: 'config/database.yml' }, { id: 'b', text: 'db/config.rb' }, { id: 'c', text: 'config/db.rb' }, { id: 'd', text: 'database.yml' }], correct_answer: 'a', explanation: 'Database configuration lives in config/database.yml.' },
  { id: 'foundation-directory-003', type: 'multiple_choice', difficulty: 1, xp_reward: 20, monster: { name: 'Migration Monster', sprite: 'migration-monster', hp: 45 }, question: 'Where are database migration files stored?', options: [{ id: 'a', text: 'app/migrations/' }, { id: 'b', text: 'db/migrate/' }, { id: 'c', text: 'config/migrations/' }, { id: 'd', text: 'migrations/' }], correct_answer: 'b', explanation: 'Migrations live in db/migrate/, timestamped for ordering.' },
  { id: 'foundation-directory-004', type: 'multiple_choice', difficulty: 1, xp_reward: 25, monster: { name: 'Route Rat', sprite: 'route-rat', hp: 45 }, question: 'Which file defines your application routes?', options: [{ id: 'a', text: 'app/routes.rb' }, { id: 'b', text: 'routes/config.rb' }, { id: 'c', text: 'config/routes.rb' }, { id: 'd', text: 'config/routing.rb' }], correct_answer: 'c', explanation: 'Routes are defined in config/routes.rb.' },
  { id: 'foundation-directory-005', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Gem Goblin', sprite: 'gem-goblin', hp: 55 }, question: 'What file lists all gem dependencies?', options: [{ id: 'a', text: 'gems.rb' }, { id: 'b', text: 'Gemfile' }, { id: 'c', text: 'config/gems.yml' }, { id: 'd', text: 'dependencies.rb' }], correct_answer: 'b', explanation: 'The Gemfile in project root lists all gem dependencies.' },
  { id: 'foundation-directory-006', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Helper Haunt', sprite: 'helper-haunt', hp: 55 }, question: 'Where would you put a helper to format currency?', options: [{ id: 'a', text: 'app/helpers/application_helper.rb' }, { id: 'b', text: 'app/controllers/application_controller.rb' }, { id: 'c', text: 'lib/formatters.rb' }, { id: 'd', text: 'app/views/helpers.rb' }], correct_answer: 'a', explanation: 'View helpers go in app/helpers/. ApplicationHelper is available to all views.' },
  { id: 'foundation-directory-007', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Asset Apparition', sprite: 'asset-apparition', hp: 60 }, question: 'In Rails 7+, where do JavaScript files typically live?', options: [{ id: 'a', text: 'app/assets/javascripts/' }, { id: 'b', text: 'app/javascript/' }, { id: 'c', text: 'public/javascripts/' }, { id: 'd', text: 'vendor/javascript/' }], correct_answer: 'b', explanation: 'Rails 7+ uses app/javascript/ with importmap or jsbundling.' },
  { id: 'foundation-directory-008', type: 'multiple_choice', difficulty: 2, xp_reward: 35, monster: { name: 'Test Troll', sprite: 'test-troll', hp: 60 }, question: 'Where do RSpec tests typically live?', options: [{ id: 'a', text: 'test/' }, { id: 'b', text: 'spec/' }, { id: 'c', text: 'app/tests/' }, { id: 'd', text: 'rspec/' }], correct_answer: 'b', explanation: 'RSpec tests go in spec/. Minitest uses test/.' },
  { id: 'foundation-directory-009', type: 'fill_in_blank', difficulty: 3, xp_reward: 40, monster: { name: 'Environment Elemental', sprite: 'env-elemental', hp: 70 }, question: 'To add production-specific configuration, edit:', code_snippet: 'config/environments/____.rb', correct_answer: 'production', explanation: 'Environment configs live in config/environments/.' },
  { id: 'foundation-directory-010', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Directory Dragon (BOSS)', sprite: 'directory-boss', hp: 100 }, question: 'Where should you place service objects?', options: [{ id: 'a', text: 'app/models/' }, { id: 'b', text: 'lib/' }, { id: 'c', text: 'app/services/ (create it)' }, { id: 'd', text: 'Both B and C are acceptable' }], correct_answer: 'd', explanation: 'Both lib/ and custom app/ directories like app/services/ work.' },

  // === FOUNDATION - ROUTING BASICS (10) ===
  { id: 'foundation-routing-001', type: 'multiple_choice', difficulty: 1, xp_reward: 20, monster: { name: 'Path Pest', sprite: 'path-pest', hp: 40 }, question: 'What does "resources :articles" generate?', options: [{ id: 'a', text: 'Only index route' }, { id: 'b', text: 'All 7 RESTful routes' }, { id: 'c', text: 'Only CRUD without index' }, { id: 'd', text: 'A single route' }], correct_answer: 'b', explanation: '"resources" generates all 7 RESTful routes.' },
  { id: 'foundation-routing-002', type: 'multiple_choice', difficulty: 1, xp_reward: 20, monster: { name: 'HTTP Hound', sprite: 'http-hound', hp: 40 }, question: 'Which HTTP verb is used for "create" action?', options: [{ id: 'a', text: 'GET' }, { id: 'b', text: 'POST' }, { id: 'c', text: 'PUT' }, { id: 'd', text: 'PATCH' }], correct_answer: 'b', explanation: 'POST is used for creating new resources.' },
  { id: 'foundation-routing-003', type: 'fill_in_blank', difficulty: 1, xp_reward: 25, monster: { name: 'Root Roach', sprite: 'root-roach', hp: 45 }, question: 'To set homepage to ArticlesController#index:', code_snippet: '____ "articles#index"', correct_answer: 'root', explanation: '"root" sets the root URL (/) of your application.' },
  { id: 'foundation-routing-004', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Verb Vulture', sprite: 'verb-vulture', hp: 55 }, question: 'What is the difference between PUT and PATCH?', options: [{ id: 'a', text: 'They are identical' }, { id: 'b', text: 'PUT replaces entire resource, PATCH updates partially' }, { id: 'c', text: 'PUT is for create' }, { id: 'd', text: 'PATCH is deprecated' }], correct_answer: 'b', explanation: 'PUT replaces entire resource, PATCH updates partially. Rails prefers PATCH.' },
  { id: 'foundation-routing-005', type: 'code_analysis', difficulty: 2, xp_reward: 30, monster: { name: 'Route Raven', sprite: 'route-raven', hp: 55 }, question: 'What URL path does this create?', code_snippet: 'get "dashboard", to: "pages#dashboard"', options: [{ id: 'a', text: '/pages/dashboard' }, { id: 'b', text: '/dashboard' }, { id: 'c', text: '/dashboard/pages' }, { id: 'd', text: '/pages#dashboard' }], correct_answer: 'b', explanation: 'First argument is URL path ("/dashboard"), "to:" specifies controller#action.' },
  { id: 'foundation-routing-006', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Singular Specter', sprite: 'singular-specter', hp: 60 }, question: 'When use "resource" (singular) vs "resources"?', options: [{ id: 'a', text: 'When only one record' }, { id: 'b', text: 'When one per user (like profile)' }, { id: 'c', text: 'When no ID needed in URL' }, { id: 'd', text: 'Both B and C' }], correct_answer: 'd', explanation: 'Singular "resource" is for things where IDs are not needed in URLs.' },
  { id: 'foundation-routing-007', type: 'fill_in_blank', difficulty: 2, xp_reward: 35, monster: { name: 'Helper Phantom', sprite: 'helper-phantom', hp: 60 }, question: 'With "resources :articles", what helper creates new article path?', code_snippet: 'link_to "New", ____', correct_answer: 'new_article_path', explanation: 'RESTful routes generate helpers: new_article_path for new.' },
  { id: 'foundation-routing-008', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Namespace Nightmare', sprite: 'namespace-nightmare', hp: 70 }, question: 'What does namespace :admin do?', code_snippet: 'namespace :admin do\n  resources :articles\nend', options: [{ id: 'a', text: 'Creates /articles with Admin:: prefix' }, { id: 'b', text: 'Creates /admin/articles expecting Admin::ArticlesController' }, { id: 'c', text: 'Requires admin auth' }, { id: 'd', text: 'Creates admin subdomain' }], correct_answer: 'b', explanation: 'Namespace adds URL prefix and expects controller in module.' },
  { id: 'foundation-routing-009', type: 'code_analysis', difficulty: 3, xp_reward: 40, monster: { name: 'Constraint Creeper', sprite: 'constraint-creeper', hp: 70 }, question: 'What command shows all routes?', options: [{ id: 'a', text: 'rails routes' }, { id: 'b', text: 'rake routes' }, { id: 'c', text: 'Both A and B' }, { id: 'd', text: 'rails show:routes' }], correct_answer: 'c', explanation: 'Both "rails routes" and "rake routes" work.' },
  { id: 'foundation-routing-010', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Route Rex (BOSS)', sprite: 'route-boss', hp: 100 }, question: 'What does "only:" do in route definitions?', code_snippet: 'resources :articles, only: [:index, :show]', options: [{ id: 'a', text: 'Filters accessible articles' }, { id: 'b', text: 'Limits which RESTful routes generated' }, { id: 'c', text: 'Adds auth requirements' }, { id: 'd', text: 'Specifies HTTP methods' }], correct_answer: 'b', explanation: '"only:" and "except:" limit which routes are generated.' },

  // === FOUNDATION - CONTROLLERS 101 (10) ===
  { id: 'foundation-controllers-001', type: 'multiple_choice', difficulty: 1, xp_reward: 20, monster: { name: 'Action Ant', sprite: 'action-ant', hp: 40 }, question: 'What is a controller "action"?', options: [{ id: 'a', text: 'A private method' }, { id: 'b', text: 'A public method that handles requests' }, { id: 'c', text: 'A callback' }, { id: 'd', text: 'A helper' }], correct_answer: 'b', explanation: 'Actions are public methods that handle HTTP requests.' },
  { id: 'foundation-controllers-002', type: 'fill_in_blank', difficulty: 1, xp_reward: 20, monster: { name: 'Instance Insect', sprite: 'instance-insect', hp: 40 }, question: 'To pass data from controller to view:', code_snippet: '____ = Article.all', correct_answer: '@articles', explanation: 'Instance variables (@ prefix) are available in views.' },
  { id: 'foundation-controllers-003', type: 'multiple_choice', difficulty: 1, xp_reward: 25, monster: { name: 'Params Parasite', sprite: 'params-parasite', hp: 45 }, question: 'How do you access form data?', options: [{ id: 'a', text: 'request.body' }, { id: 'b', text: 'params' }, { id: 'c', text: 'form_data' }, { id: 'd', text: '@params' }], correct_answer: 'b', explanation: '"params" contains all request parameters.' },
  { id: 'foundation-controllers-004', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Render Reptile', sprite: 'render-reptile', hp: 55 }, question: 'What happens if no render/redirect in action?', options: [{ id: 'a', text: 'Error raised' }, { id: 'b', text: 'Rails renders view matching action name' }, { id: 'c', text: 'Blank page' }, { id: 'd', text: 'Redirects to root' }], correct_answer: 'b', explanation: 'Rails implicitly renders view with same name as action.' },
  { id: 'foundation-controllers-005', type: 'code_analysis', difficulty: 2, xp_reward: 30, monster: { name: 'Redirect Rodent', sprite: 'redirect-rodent', hp: 55 }, question: 'Difference between render and redirect_to?', options: [{ id: 'a', text: 'Same thing' }, { id: 'b', text: 'render shows view, redirect_to sends new request' }, { id: 'c', text: 'render for HTML, redirect_to for JSON' }, { id: 'd', text: 'redirect_to is deprecated' }], correct_answer: 'b', explanation: 'render displays template, redirect_to sends 302 response.' },
  { id: 'foundation-controllers-006', type: 'fill_in_blank', difficulty: 2, xp_reward: 30, monster: { name: 'Before Beast', sprite: 'before-beast', hp: 60 }, question: 'To run code before every action:', code_snippet: '____ :authenticate_user', correct_answer: 'before_action', explanation: 'before_action runs specified method before actions.' },
  { id: 'foundation-controllers-007', type: 'multiple_choice', difficulty: 2, xp_reward: 35, monster: { name: 'Status Specter', sprite: 'status-specter', hp: 60 }, question: 'How to return 404 Not Found?', options: [{ id: 'a', text: 'render status: 404' }, { id: 'b', text: 'head :not_found' }, { id: 'c', text: 'raise ActiveRecord::RecordNotFound' }, { id: 'd', text: 'All of the above' }], correct_answer: 'd', explanation: 'All three work. RecordNotFound is idiomatic in Rails.' },
  { id: 'foundation-controllers-008', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'JSON Jackal', sprite: 'json-jackal', hp: 70 }, question: 'How to respond with JSON?', options: [{ id: 'a', text: 'render json: @article' }, { id: 'b', text: 'respond_to { |f| f.json { render json: @article } }' }, { id: 'c', text: 'Both A and B' }, { id: 'd', text: 'return @article.to_json' }], correct_answer: 'c', explanation: 'Both work. "render json:" is simpler.' },
  { id: 'foundation-controllers-009', type: 'code_analysis', difficulty: 3, xp_reward: 40, monster: { name: 'Private Poltergeist', sprite: 'private-poltergeist', hp: 70 }, question: 'Why are strong params private methods?', code_snippet: 'private\ndef article_params\n  params.require(:article).permit(:title)\nend', options: [{ id: 'a', text: 'Prevents them from being called as actions' }, { id: 'b', text: 'Just convention' }, { id: 'c', text: 'Faster execution' }, { id: 'd', text: 'Hides from router' }], correct_answer: 'a', explanation: 'Private methods cannot be routed to as actions.' },
  { id: 'foundation-controllers-010', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Controller King (BOSS)', sprite: 'controller-boss', hp: 100 }, question: 'What is ApplicationController for?', options: [{ id: 'a', text: 'Entry point for requests' }, { id: 'b', text: 'Base class for shared controller logic' }, { id: 'c', text: 'Application configuration' }, { id: 'd', text: 'Manages app lifecycle' }], correct_answer: 'b', explanation: 'ApplicationController is base class for all controllers.' },

  // === FOUNDATION - VIEWS & ERB (10) ===
  { id: 'foundation-views-001', type: 'multiple_choice', difficulty: 1, xp_reward: 20, monster: { name: 'ERB Elf', sprite: 'erb-elf', hp: 40 }, question: 'What does ERB stand for?', options: [{ id: 'a', text: 'Embedded Ruby' }, { id: 'b', text: 'Extended Ruby Base' }, { id: 'c', text: 'Evaluated Ruby Blocks' }, { id: 'd', text: 'Enhanced Ruby Builder' }], correct_answer: 'a', explanation: 'ERB stands for Embedded Ruby.' },
  { id: 'foundation-views-002', type: 'multiple_choice', difficulty: 1, xp_reward: 20, monster: { name: 'Tag Terror', sprite: 'tag-terror', hp: 40 }, question: 'Difference between <%= %> and <% %>?', options: [{ id: 'a', text: 'No difference' }, { id: 'b', text: '<%= %> outputs, <% %> executes without output' }, { id: 'c', text: '<%= %> for strings, <% %> for numbers' }, { id: 'd', text: '<% %> outputs' }], correct_answer: 'b', explanation: '<%= %> outputs result, <% %> executes without outputting.' },
  { id: 'foundation-views-003', type: 'fill_in_blank', difficulty: 1, xp_reward: 25, monster: { name: 'Partial Pixie', sprite: 'partial-pixie', hp: 45 }, question: 'To render "_sidebar.html.erb":', code_snippet: '<%= render partial: "____" %>', correct_answer: 'sidebar', explanation: 'Partials have underscore prefix but referenced without it.' },
  { id: 'foundation-views-004', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'XSS Xenomorph', sprite: 'xss-xeno', hp: 55 }, question: 'Why does Rails auto-escape HTML in <%= %>?', options: [{ id: 'a', text: 'Performance' }, { id: 'b', text: 'Prevent XSS attacks' }, { id: 'c', text: 'Ensure valid HTML' }, { id: 'd', text: 'It does not escape' }], correct_answer: 'b', explanation: 'Rails escapes HTML to prevent XSS attacks.' },
  { id: 'foundation-views-005', type: 'code_analysis', difficulty: 2, xp_reward: 30, monster: { name: 'Link Lurker', sprite: 'link-lurker', hp: 55 }, question: 'What HTML does this generate?', code_snippet: '<%= link_to "Home", root_path, class: "nav" %>', options: [{ id: 'a', text: '<a href="/" class="nav">Home</a>' }, { id: 'b', text: '<link href="/">Home</link>' }, { id: 'c', text: '<a class="nav">Home</a>' }, { id: 'd', text: '<button>Home</button>' }], correct_answer: 'a', explanation: 'link_to generates anchor tag with href and attributes.' },
  { id: 'foundation-views-006', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Layout Lich', sprite: 'layout-lich', hp: 60 }, question: 'What does "yield" do in a layout?', options: [{ id: 'a', text: 'Returns to controller' }, { id: 'b', text: 'Inserts view content' }, { id: 'c', text: 'Yields to JavaScript' }, { id: 'd', text: 'Pauses rendering' }], correct_answer: 'b', explanation: '"yield" marks where view content goes in the layout.' },
  { id: 'foundation-views-007', type: 'fill_in_blank', difficulty: 2, xp_reward: 35, monster: { name: 'Form Phantom', sprite: 'form-phantom', hp: 60 }, question: 'To create form for new @article:', code_snippet: '<%= form_with model: ____ do |f| %>', correct_answer: '@article', explanation: 'form_with model: @article auto-sets action and method.' },
  { id: 'foundation-views-008', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Collection Cobra', sprite: 'collection-cobra', hp: 70 }, question: 'More efficient way to render collection?', code_snippet: '<% @articles.each do |a| %>\n  <%= render "article", article: a %>\n<% end %>', options: [{ id: 'a', text: 'Cannot improve' }, { id: 'b', text: '<%= render @articles %>' }, { id: 'c', text: '<%= render collection: @articles %>' }, { id: 'd', text: 'Both B and C' }], correct_answer: 'd', explanation: 'Both render @articles and render collection: work efficiently.' },
  { id: 'foundation-views-009', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Content Chimera', sprite: 'content-chimera', hp: 70 }, question: 'How to add content to named yield section?', options: [{ id: 'a', text: '<% sidebar do %>' }, { id: 'b', text: '<% content_for :sidebar do %>' }, { id: 'c', text: '<%= yield_to :sidebar do %>' }, { id: 'd', text: '<%= render :sidebar do %>' }], correct_answer: 'b', explanation: 'content_for captures content for matching yield :name.' },
  { id: 'foundation-views-010', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'View Overlord (BOSS)', sprite: 'view-boss', hp: 100 }, question: 'How to safely output trusted raw HTML?', options: [{ id: 'a', text: 'raw()' }, { id: 'b', text: 'html_safe' }, { id: 'c', text: 'sanitize()' }, { id: 'd', text: 'All with different safety levels' }], correct_answer: 'd', explanation: 'raw/html_safe mark as safe, sanitize strips dangerous tags.' },

  // === ACTIVERECORD - MODELS (10) ===
  { id: 'activerecord-models-001', type: 'multiple_choice', difficulty: 1, xp_reward: 25, monster: { name: 'Migration Mimic', sprite: 'migration-mimic', hp: 50 }, question: 'What command generates a new model with migration?', options: [{ id: 'a', text: 'rails new model Article' }, { id: 'b', text: 'rails generate model Article title:string' }, { id: 'c', text: 'rails create Article' }, { id: 'd', text: 'rails model Article' }], correct_answer: 'b', explanation: 'rails generate model creates model and migration.' },
  { id: 'activerecord-models-002', type: 'fill_in_blank', difficulty: 1, xp_reward: 25, monster: { name: 'Table Troll', sprite: 'table-troll', hp: 50 }, question: 'Model "Article" maps to which table?', code_snippet: 'Table: ____', correct_answer: 'articles', explanation: 'Rails pluralizes/lowercases: Article -> articles.' },
  { id: 'activerecord-models-003', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Schema Shade', sprite: 'schema-shade', hp: 60 }, question: 'What does "rails db:migrate" do?', options: [{ id: 'a', text: 'Creates database' }, { id: 'b', text: 'Runs pending migrations to update schema' }, { id: 'c', text: 'Exports data' }, { id: 'd', text: 'Deletes tables' }], correct_answer: 'b', explanation: 'db:migrate runs all pending migrations.' },
  { id: 'activerecord-models-004', type: 'code_analysis', difficulty: 2, xp_reward: 30, monster: { name: 'Column Crawler', sprite: 'column-crawler', hp: 60 }, question: 'What does this migration do?', code_snippet: 'add_column :articles, :published_at, :datetime\nadd_index :articles, :published_at', options: [{ id: 'a', text: 'Creates articles table' }, { id: 'b', text: 'Adds column and index' }, { id: 'c', text: 'Removes column' }, { id: 'd', text: 'Renames column' }], correct_answer: 'b', explanation: 'add_column adds column, add_index creates database index.' },
  { id: 'activerecord-models-005', type: 'multiple_choice', difficulty: 2, xp_reward: 35, monster: { name: 'Rollback Revenant', sprite: 'rollback-revenant', hp: 65 }, question: 'How to undo the last migration?', options: [{ id: 'a', text: 'rails db:undo' }, { id: 'b', text: 'rails db:rollback' }, { id: 'c', text: 'rails db:migrate:down' }, { id: 'd', text: 'rails db:reverse' }], correct_answer: 'b', explanation: 'db:rollback reverses the last migration.' },
  { id: 'activerecord-models-006', type: 'fill_in_blank', difficulty: 2, xp_reward: 35, monster: { name: 'Primary Phantom', sprite: 'primary-phantom', hp: 65 }, question: 'ActiveRecord auto-creates which primary key column?', code_snippet: 'Column: ____', correct_answer: 'id', explanation: 'Rails adds "id" as auto-incrementing primary key.' },
  { id: 'activerecord-models-007', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Reference Reaper', sprite: 'reference-reaper', hp: 75 }, question: 'What does "t.references :user" do?', options: [{ id: 'a', text: 'Creates user_id column and index' }, { id: 'b', text: 'Creates foreign key only' }, { id: 'c', text: 'Links via URL' }, { id: 'd', text: 'Creates user column' }], correct_answer: 'a', explanation: 't.references creates user_id, index, and optional foreign key.' },
  { id: 'activerecord-models-008', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Timestamp Terror', sprite: 'timestamp-terror', hp: 75 }, question: 'What do created_at/updated_at do?', options: [{ id: 'a', text: 'Must update manually' }, { id: 'b', text: 'Rails auto-sets on create/update' }, { id: 'c', text: 'Optional and unused' }, { id: 'd', text: 'Track who created/updated' }], correct_answer: 'b', explanation: 'These "magic" columns are automatically managed by Rails.' },
  { id: 'activerecord-models-009', type: 'code_analysis', difficulty: 3, xp_reward: 45, monster: { name: 'Irreversible Imp', sprite: 'irreversible-imp', hp: 80 }, question: 'Why might this cause problems?', code_snippet: 'def change\n  remove_column :users, :email\nend', options: [{ id: 'a', text: 'Perfectly fine' }, { id: 'b', text: 'Cannot reverse without column type' }, { id: 'c', text: 'remove_column does not exist' }, { id: 'd', text: 'Cannot remove columns' }], correct_answer: 'b', explanation: 'Specify type for reversible: remove_column :users, :email, :string' },
  { id: 'activerecord-models-010', type: 'multiple_choice', difficulty: 3, xp_reward: 50, monster: { name: 'Model Monarch (BOSS)', sprite: 'model-boss', hp: 110 }, question: 'What file shows current database schema?', options: [{ id: 'a', text: 'db/schema.rb' }, { id: 'b', text: 'config/database.yml' }, { id: 'c', text: 'app/models/schema.rb' }, { id: 'd', text: 'db/migrate/schema.rb' }], correct_answer: 'a', explanation: 'db/schema.rb shows current database structure.' },

  // === ACTIVERECORD - ASSOCIATIONS (10) ===
  { id: 'activerecord-associations-001', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Orphan Ogre', sprite: 'orphan-ogre', hp: 60 }, question: 'Which side of one-to-many has the foreign key?', options: [{ id: 'a', text: 'has_many side' }, { id: 'b', text: 'belongs_to side' }, { id: 'c', text: 'Both' }, { id: 'd', text: 'Neither' }], correct_answer: 'b', explanation: 'belongs_to side holds foreign key (comments table has article_id).' },
  { id: 'activerecord-associations-002', type: 'fill_in_blank', difficulty: 2, xp_reward: 30, monster: { name: 'Foreign Key Fiend', sprite: 'fk-fiend', hp: 60 }, question: 'If Comment belongs_to Article, what column needed?', code_snippet: 'Column: ____', correct_answer: 'article_id', explanation: 'Convention: foreign key is singular model name + _id.' },
  { id: 'activerecord-associations-003', type: 'code_analysis', difficulty: 2, xp_reward: 35, monster: { name: 'Dependency Demon', sprite: 'dependency-demon', hp: 65 }, question: 'What does "dependent: :destroy" do?', code_snippet: 'has_many :books, dependent: :destroy', options: [{ id: 'a', text: 'Destroys author when book deleted' }, { id: 'b', text: 'Destroys all books when author deleted' }, { id: 'c', text: 'Prevents author deletion' }, { id: 'd', text: 'Marks books deleted' }], correct_answer: 'b', explanation: 'dependent: :destroy cascades deletion to associated records.' },
  { id: 'activerecord-associations-004', type: 'multiple_choice', difficulty: 2, xp_reward: 35, monster: { name: 'Many Menace', sprite: 'many-menace', hp: 65 }, question: 'For many-to-many, which associations?', options: [{ id: 'a', text: 'has_many on both' }, { id: 'b', text: 'has_many :through on both with join model' }, { id: 'c', text: 'belongs_to on both' }, { id: 'd', text: 'has_one on both' }], correct_answer: 'b', explanation: 'has_many :through uses a join model.' },
  { id: 'activerecord-associations-005', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Polymorphic Phantom', sprite: 'poly-phantom', hp: 75 }, question: 'When use polymorphic association?', options: [{ id: 'a', text: 'Model can belong to multiple types' }, { id: 'b', text: 'Need multiple foreign keys' }, { id: 'c', text: 'Models share table' }, { id: 'd', text: 'Avoid foreign keys' }], correct_answer: 'a', explanation: 'Polymorphic lets model belong to multiple types.' },
  { id: 'activerecord-associations-006', type: 'code_analysis', difficulty: 3, xp_reward: 40, monster: { name: 'Through Thorn', sprite: 'through-thorn', hp: 75 }, question: 'What does has_many :through allow?', code_snippet: 'has_many :appointments\nhas_many :patients, through: :appointments', options: [{ id: 'a', text: 'doctor.patients returns all patients' }, { id: 'b', text: 'Creates patients column' }, { id: 'c', text: 'Makes appointments unavailable' }, { id: 'd', text: 'Removes appointments table' }], correct_answer: 'a', explanation: 'has_many :through lets you access through join model.' },
  { id: 'activerecord-associations-007', type: 'fill_in_blank', difficulty: 3, xp_reward: 40, monster: { name: 'Inverse Imp', sprite: 'inverse-imp', hp: 80 }, question: 'To avoid extra queries, specify:', code_snippet: 'has_many :comments, ____: :article', correct_answer: 'inverse_of', explanation: 'inverse_of tells Rails the reciprocal association.' },
  { id: 'activerecord-associations-008', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Self-Join Serpent', sprite: 'selfjoin-serpent', hp: 80 }, question: 'How model employees with managers (also employees)?', options: [{ id: 'a', text: 'Separate managers table' }, { id: 'b', text: 'Self-referential with manager_id' }, { id: 'c', text: 'Polymorphic association' }, { id: 'd', text: 'Not possible' }], correct_answer: 'b', explanation: 'Self-referential: belongs_to :manager, class_name: "Employee".' },
  { id: 'activerecord-associations-009', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Counter Creature', sprite: 'counter-creature', hp: 85 }, question: 'What does "counter_cache: true" do?', options: [{ id: 'a', text: 'Caches article in memory' }, { id: 'b', text: 'Maintains comments_count column' }, { id: 'c', text: 'Limits comments' }, { id: 'd', text: 'Speeds up queries' }], correct_answer: 'b', explanation: 'Counter cache maintains count column on parent.' },
  { id: 'activerecord-associations-010', type: 'multiple_choice', difficulty: 4, xp_reward: 50, monster: { name: 'Association Archon (BOSS)', sprite: 'association-boss', hp: 120 }, question: 'Difference between has_many :through and HABTM?', options: [{ id: 'a', text: 'No difference' }, { id: 'b', text: ':through uses join model, HABTM uses simple table' }, { id: 'c', text: 'HABTM is faster' }, { id: 'd', text: ':through is deprecated' }], correct_answer: 'b', explanation: 'has_many :through uses full model, HABTM uses simple join table.' },

  // === ACTIVERECORD - VALIDATIONS (10) ===
  { id: 'activerecord-validations-001', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Blank Bug', sprite: 'blank-bug', hp: 55 }, question: 'Which validation ensures field is not empty?', options: [{ id: 'a', text: 'validates :title, required: true' }, { id: 'b', text: 'validates :title, presence: true' }, { id: 'c', text: 'validates :title, not_empty: true' }, { id: 'd', text: 'validates :title, exists: true' }], correct_answer: 'b', explanation: 'presence: true ensures attribute is not blank.' },
  { id: 'activerecord-validations-002', type: 'fill_in_blank', difficulty: 2, xp_reward: 30, monster: { name: 'Unique Unicorn', sprite: 'unique-unicorn', hp: 55 }, question: 'To ensure emails are unique:', code_snippet: 'validates :email, ____: true', correct_answer: 'uniqueness', explanation: 'uniqueness: true checks database for existing value.' },
  { id: 'activerecord-validations-003', type: 'multiple_choice', difficulty: 2, xp_reward: 35, monster: { name: 'Length Leech', sprite: 'length-leech', hp: 60 }, question: 'Validate title between 5 and 100 characters?', options: [{ id: 'a', text: 'validates :title, length: { minimum: 5, maximum: 100 }' }, { id: 'b', text: 'validates :title, length: 5..100' }, { id: 'c', text: 'validates :title, size: { min: 5, max: 100 }' }, { id: 'd', text: 'validates :title, chars: { from: 5, to: 100 }' }], correct_answer: 'a', explanation: 'length accepts minimum:, maximum:, is:, in:, within:.' },
  { id: 'activerecord-validations-004', type: 'multiple_choice', difficulty: 2, xp_reward: 35, monster: { name: 'Format Fiend', sprite: 'format-fiend', hp: 60 }, question: 'How validate email format with regex?', options: [{ id: 'a', text: 'validates :email, regex: EMAIL_REGEX' }, { id: 'b', text: 'validates :email, format: { with: EMAIL_REGEX }' }, { id: 'c', text: 'validates :email, pattern: EMAIL_REGEX' }, { id: 'd', text: 'validates :email, match: EMAIL_REGEX' }], correct_answer: 'b', explanation: 'format: { with: /regex/ } validates against pattern.' },
  { id: 'activerecord-validations-005', type: 'code_analysis', difficulty: 3, xp_reward: 40, monster: { name: 'Numericality Nightmare', sprite: 'numeric-nightmare', hp: 70 }, question: 'What does this ensure?', code_snippet: 'validates :age, numericality: { greater_than_or_equal_to: 0, only_integer: true }', options: [{ id: 'a', text: 'Any positive number' }, { id: 'b', text: 'Non-negative integer' }, { id: 'c', text: 'Greater than 0' }, { id: 'd', text: 'Optional but numeric' }], correct_answer: 'b', explanation: 'Allows 0+, rejects decimals: 0, 1, 2... not -1 or 1.5.' },
  { id: 'activerecord-validations-006', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Conditional Chimera', sprite: 'conditional-chimera', hp: 70 }, question: 'Validate bio presence only if admin?', options: [{ id: 'a', text: 'validates :bio, presence: true, when: :admin?' }, { id: 'b', text: 'validates :bio, presence: true, if: :admin?' }, { id: 'c', text: 'validates :bio, presence: { if: :admin? }' }, { id: 'd', text: 'validates :bio, presence: true, only: :admin' }], correct_answer: 'b', explanation: 'if: :method_name makes validation conditional.' },
  { id: 'activerecord-validations-007', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Error Elemental', sprite: 'error-elemental', hp: 75 }, question: 'How access validation errors after save fails?', options: [{ id: 'a', text: 'article.validation_errors' }, { id: 'b', text: 'article.errors' }, { id: 'c', text: 'article.error_messages' }, { id: 'd', text: 'Article.errors' }], correct_answer: 'b', explanation: 'article.errors returns ActiveModel::Errors object.' },
  { id: 'activerecord-validations-008', type: 'fill_in_blank', difficulty: 3, xp_reward: 45, monster: { name: 'Custom Creature', sprite: 'custom-creature', hp: 75 }, question: 'To add custom validation method:', code_snippet: '____ :must_have_valid_slug', correct_answer: 'validate', explanation: '"validate" (singular) for custom methods.' },
  { id: 'activerecord-validations-009', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Skip Specter', sprite: 'skip-specter', hp: 80 }, question: 'Save record while skipping validations?', options: [{ id: 'a', text: 'article.save(skip_validations: true)' }, { id: 'b', text: 'article.save(validate: false)' }, { id: 'c', text: 'article.save!' }, { id: 'd', text: 'article.force_save' }], correct_answer: 'b', explanation: 'save(validate: false) skips validations. Use cautiously.' },
  { id: 'activerecord-validations-010', type: 'multiple_choice', difficulty: 4, xp_reward: 50, monster: { name: 'Validation Overlord (BOSS)', sprite: 'validation-boss', hp: 120 }, question: 'Difference between save and save!?', options: [{ id: 'a', text: 'save! is faster' }, { id: 'b', text: 'save returns true/false, save! raises exception' }, { id: 'c', text: 'save! skips callbacks' }, { id: 'd', text: 'No difference' }], correct_answer: 'b', explanation: 'save returns false on failure, save! raises RecordInvalid.' },

  // === ACTIVERECORD - CALLBACKS (10) ===
  { id: 'activerecord-callbacks-001', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Before Beast', sprite: 'before-beast', hp: 55 }, question: 'When does "before_save" run?', options: [{ id: 'a', text: 'Only before create' }, { id: 'b', text: 'Only before update' }, { id: 'c', text: 'Before both create and update' }, { id: 'd', text: 'After save' }], correct_answer: 'c', explanation: 'before_save runs before both create and update.' },
  { id: 'activerecord-callbacks-002', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'After Apparition', sprite: 'after-apparition', hp: 55 }, question: 'Which callback runs after record saved to database?', options: [{ id: 'a', text: 'after_save' }, { id: 'b', text: 'after_commit' }, { id: 'c', text: 'Both, but after_commit waits for commit' }, { id: 'd', text: 'after_persist' }], correct_answer: 'c', explanation: 'after_save in transaction, after_commit after commit.' },
  { id: 'activerecord-callbacks-003', type: 'fill_in_blank', difficulty: 2, xp_reward: 35, monster: { name: 'Validation Vampire', sprite: 'validation-vampire', hp: 60 }, question: 'To run code before validations:', code_snippet: '____ :normalize_email', correct_answer: 'before_validation', explanation: 'before_validation is perfect for normalizing data.' },
  { id: 'activerecord-callbacks-004', type: 'code_analysis', difficulty: 3, xp_reward: 40, monster: { name: 'Halt Hydra', sprite: 'halt-hydra', hp: 70 }, question: 'If before_save returns false?', code_snippet: 'before_save :check\ndef check\n  false\nend', options: [{ id: 'a', text: 'Save continues' }, { id: 'b', text: 'Save is halted' }, { id: 'c', text: 'Exception raised' }, { id: 'd', text: 'Only Rails 4' }], correct_answer: 'b', explanation: 'In Rails 5+, use "throw :abort" to halt. false just returns.' },
  { id: 'activerecord-callbacks-005', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Destroy Dragon', sprite: 'destroy-dragon', hp: 70 }, question: 'Difference: before_destroy vs dependent: :destroy?', options: [{ id: 'a', text: 'Same thing' }, { id: 'b', text: 'before_destroy is callback, dependent handles associations' }, { id: 'c', text: 'before_destroy deprecated' }, { id: 'd', text: 'dependent is a callback' }], correct_answer: 'b', explanation: 'before_destroy is lifecycle callback, dependent is association option.' },
  { id: 'activerecord-callbacks-006', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Transaction Terror', sprite: 'transaction-terror', hp: 75 }, question: 'When use after_commit vs after_save?', options: [{ id: 'a', text: 'For faster execution' }, { id: 'b', text: 'For external services (emails, jobs)' }, { id: 'c', text: 'For updating other models' }, { id: 'd', text: 'Always use after_save' }], correct_answer: 'b', explanation: 'after_commit runs after transaction commits - safe for external actions.' },
  { id: 'activerecord-callbacks-007', type: 'fill_in_blank', difficulty: 3, xp_reward: 45, monster: { name: 'Conditional Creature', sprite: 'conditional-creature', hp: 75 }, question: 'Run callback only when attribute changes:', code_snippet: 'after_save :notify, if: :____', correct_answer: 'saved_change_to_status?', explanation: 'saved_change_to_attribute? checks if changed during save.' },
  { id: 'activerecord-callbacks-008', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Touch Troll', sprite: 'touch-troll', hp: 80 }, question: 'Which callback does update_column skip?', options: [{ id: 'a', text: 'before_save' }, { id: 'b', text: 'after_save' }, { id: 'c', text: 'All callbacks are skipped' }, { id: 'd', text: 'Only after_commit' }], correct_answer: 'c', explanation: 'update_column bypasses validations AND all callbacks.' },
  { id: 'activerecord-callbacks-009', type: 'multiple_choice', difficulty: 4, xp_reward: 50, monster: { name: 'Order Ogre', sprite: 'order-ogre', hp: 85 }, question: 'Correct callback order when creating?', options: [{ id: 'a', text: 'before_validation -> before_save -> before_create -> after_create -> after_save -> after_commit' }, { id: 'b', text: 'before_save -> before_validation -> after_save' }, { id: 'c', text: 'before_create -> before_save -> after_create' }, { id: 'd', text: 'before_validation -> before_create -> before_save' }], correct_answer: 'a', explanation: 'Order: validation -> save (around create) -> commit callbacks.' },
  { id: 'activerecord-callbacks-010', type: 'multiple_choice', difficulty: 4, xp_reward: 55, monster: { name: 'Callback Colossus (BOSS)', sprite: 'callback-boss', hp: 130 }, question: 'Why might heavy callback logic be anti-pattern?', options: [{ id: 'a', text: 'Callbacks are slow' }, { id: 'b', text: 'Hard to test, hidden side effects' }, { id: 'c', text: 'Do not work in production' }, { id: 'd', text: 'Rails discourages them' }], correct_answer: 'b', explanation: 'Heavy callbacks create hidden side effects. Consider service objects.' },

  // === ACTIVERECORD - QUERIES (10) ===
  { id: 'activerecord-queries-001', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Find Fiend', sprite: 'find-fiend', hp: 55 }, question: 'Difference between find and find_by?', options: [{ id: 'a', text: 'find uses ID, find_by any attribute' }, { id: 'b', text: 'find_by is deprecated' }, { id: 'c', text: 'find returns array' }, { id: 'd', text: 'A, and find raises if not found, find_by returns nil' }], correct_answer: 'd', explanation: 'find raises RecordNotFound, find_by returns nil.' },
  { id: 'activerecord-queries-002', type: 'fill_in_blank', difficulty: 2, xp_reward: 30, monster: { name: 'Where Wolf', sprite: 'where-wolf', hp: 55 }, question: 'To find all published articles:', code_snippet: 'Article.____(published: true)', correct_answer: 'where', explanation: 'where returns ActiveRecord::Relation with matching records.' },
  { id: 'activerecord-queries-003', type: 'multiple_choice', difficulty: 2, xp_reward: 35, monster: { name: 'Order Orc', sprite: 'order-orc', hp: 60 }, question: 'Order articles by created_at descending?', options: [{ id: 'a', text: 'Article.order(:created_at, :desc)' }, { id: 'b', text: 'Article.order(created_at: :desc)' }, { id: 'c', text: 'Article.sort(created_at: :desc)' }, { id: 'd', text: 'Article.order_by(:created_at).desc' }], correct_answer: 'b', explanation: 'order(column: :direction) sorts results.' },
  { id: 'activerecord-queries-004', type: 'code_analysis', difficulty: 2, xp_reward: 35, monster: { name: 'N+1 Nightmare', sprite: 'n1-nightmare', hp: 65 }, question: 'What problem here?', code_snippet: '@articles = Article.all\n@articles.each { |a| puts a.author.name }', options: [{ id: 'a', text: 'Syntax error' }, { id: 'b', text: 'N+1 query problem' }, { id: 'c', text: 'Memory leak' }, { id: 'd', text: 'No problem' }], correct_answer: 'b', explanation: 'N+1: 1 query for articles + N for authors. Fix with includes(:author).' },
  { id: 'activerecord-queries-005', type: 'fill_in_blank', difficulty: 3, xp_reward: 40, monster: { name: 'Eager Elemental', sprite: 'eager-elemental', hp: 70 }, question: 'Eager load authors (prevent N+1):', code_snippet: 'Article.____(:author).all', correct_answer: 'includes', explanation: 'includes eager loads associations.' },
  { id: 'activerecord-queries-006', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Scope Specter', sprite: 'scope-specter', hp: 70 }, question: 'Benefit of using scopes?', code_snippet: 'scope :published, -> { where(published: true) }', options: [{ id: 'a', text: 'Faster than where' }, { id: 'b', text: 'Reusable, chainable, keeps logic in model' }, { id: 'c', text: 'Auto-caches results' }, { id: 'd', text: 'Required for complex queries' }], correct_answer: 'b', explanation: 'Scopes encapsulate query logic, reusable and chainable.' },
  { id: 'activerecord-queries-007', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Pluck Poltergeist', sprite: 'pluck-poltergeist', hp: 75 }, question: 'Advantage of pluck over map?', code_snippet: 'Article.pluck(:title) vs Article.all.map(&:title)', options: [{ id: 'a', text: 'pluck returns AR objects' }, { id: 'b', text: 'pluck queries only needed columns, less memory' }, { id: 'c', text: 'map is always better' }, { id: 'd', text: 'No difference' }], correct_answer: 'b', explanation: 'pluck selects only specified columns, returns plain values.' },
  { id: 'activerecord-queries-008', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Batch Beast', sprite: 'batch-beast', hp: 80 }, question: 'Process 1 million records without memory issues?', options: [{ id: 'a', text: 'Article.all.each { |a| process(a) }' }, { id: 'b', text: 'Article.find_each { |a| process(a) }' }, { id: 'c', text: 'Article.limit(1000000).each' }, { id: 'd', text: 'Use raw SQL' }], correct_answer: 'b', explanation: 'find_each loads records in batches (default 1000).' },
  { id: 'activerecord-queries-009', type: 'code_analysis', difficulty: 4, xp_reward: 50, monster: { name: 'Join Juggernaut', sprite: 'join-juggernaut', hp: 85 }, question: 'Difference between joins and includes?', options: [{ id: 'a', text: 'joins filters with INNER JOIN, includes eager loads' }, { id: 'b', text: 'Same thing' }, { id: 'c', text: 'includes does INNER JOIN' }, { id: 'd', text: 'joins eager loads' }], correct_answer: 'a', explanation: 'joins does INNER JOIN for filtering, includes eager loads.' },
  { id: 'activerecord-queries-010', type: 'multiple_choice', difficulty: 4, xp_reward: 55, monster: { name: 'Query Overlord (BOSS)', sprite: 'query-boss', hp: 130 }, question: 'When use exists? instead of present?', options: [{ id: 'a', text: 'exists? only checks existence without loading' }, { id: 'b', text: 'present? is always better' }, { id: 'c', text: 'exists? loads all records' }, { id: 'd', text: 'No difference' }], correct_answer: 'a', explanation: 'exists? uses SELECT 1 LIMIT 1, very fast. present? loads records.' },

  // === ROUTING - RESTFUL (10) ===
  { id: 'routing-restful-001', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'REST Wraith', sprite: 'rest-wraith', hp: 60 }, question: 'How many routes does "resources :articles" generate?', options: [{ id: 'a', text: '4' }, { id: 'b', text: '5' }, { id: 'c', text: '7' }, { id: 'd', text: '8' }], correct_answer: 'c', explanation: 'resources generates 7 routes: index, show, new, create, edit, update, destroy.' },
  { id: 'routing-restful-002', type: 'fill_in_blank', difficulty: 2, xp_reward: 30, monster: { name: 'Verb Vulture', sprite: 'verb-vulture', hp: 60 }, question: 'The "destroy" action uses which HTTP verb?', code_snippet: 'HTTP Verb: ____', correct_answer: 'DELETE', explanation: 'DELETE for destroy. GET, POST, PATCH/PUT for others.' },
  { id: 'routing-restful-003', type: 'code_analysis', difficulty: 2, xp_reward: 35, monster: { name: 'Path Phantom', sprite: 'path-phantom', hp: 65 }, question: 'What URL for edit_article_path(@article) if id=5?', options: [{ id: 'a', text: '/articles/5/edit' }, { id: 'b', text: '/articles/edit/5' }, { id: 'c', text: '/edit/articles/5' }, { id: 'd', text: '/articles/5' }], correct_answer: 'a', explanation: 'RESTful edit path is /resource/:id/edit.' },
  { id: 'routing-restful-004', type: 'multiple_choice', difficulty: 2, xp_reward: 35, monster: { name: 'Only Ogre', sprite: 'only-ogre', hp: 65 }, question: 'Generate only index and show routes?', options: [{ id: 'a', text: 'resources :articles, actions: [:index, :show]' }, { id: 'b', text: 'resources :articles, only: [:index, :show]' }, { id: 'c', text: 'resources :articles { index; show }' }, { id: 'd', text: 'get_resources :articles' }], correct_answer: 'b', explanation: 'only: limits which routes are generated.' },
  { id: 'routing-restful-005', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Member Monster', sprite: 'member-monster', hp: 70 }, question: 'Difference between member and collection routes?', options: [{ id: 'a', text: 'member requires ID, collection does not' }, { id: 'b', text: 'collection requires ID' }, { id: 'c', text: 'Same thing' }, { id: 'd', text: 'member for GET, collection for POST' }], correct_answer: 'a', explanation: 'member acts on one (/articles/5/publish), collection on all (/articles/search).' },
  { id: 'routing-restful-006', type: 'code_analysis', difficulty: 3, xp_reward: 40, monster: { name: 'Collection Creature', sprite: 'collection-creature', hp: 75 }, question: 'What route does this create?', code_snippet: 'resources :articles do\n  collection do\n    get "search"\n  end\nend', options: [{ id: 'a', text: 'GET /articles/:id/search' }, { id: 'b', text: 'GET /articles/search' }, { id: 'c', text: 'GET /search/articles' }, { id: 'd', text: 'POST /articles/search' }], correct_answer: 'b', explanation: 'collection routes have no :id. Creates GET /articles/search.' },
  { id: 'routing-restful-007', type: 'fill_in_blank', difficulty: 3, xp_reward: 45, monster: { name: 'Singular Serpent', sprite: 'singular-serpent', hp: 75 }, question: 'For single resource per user (like profile):', code_snippet: '____ :profile', correct_answer: 'resource', explanation: 'resource (singular) creates routes without IDs.' },
  { id: 'routing-restful-008', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Shallow Shadow', sprite: 'shallow-shadow', hp: 80 }, question: 'What does "shallow: true" do in nested resources?', options: [{ id: 'a', text: 'Removes all nested routes' }, { id: 'b', text: 'Un-nests show/edit/update/destroy' }, { id: 'c', text: 'One level nesting only' }, { id: 'd', text: 'Case-insensitive routes' }], correct_answer: 'b', explanation: 'shallow keeps index/new/create nested, un-nests show/edit/update/destroy.' },
  { id: 'routing-restful-009', type: 'multiple_choice', difficulty: 4, xp_reward: 50, monster: { name: 'API Apparition', sprite: 'api-apparition', hp: 85 }, question: 'For API, generate routes without new/edit?', options: [{ id: 'a', text: 'resources :articles, api: true' }, { id: 'b', text: 'resources :articles, except: [:new, :edit]' }, { id: 'c', text: 'api_resources :articles' }, { id: 'd', text: 'resources :articles, format: :json' }], correct_answer: 'b', explanation: 'APIs do not need new/edit (form pages). Use except: [:new, :edit].' },
  { id: 'routing-restful-010', type: 'multiple_choice', difficulty: 4, xp_reward: 55, monster: { name: 'RESTful Ruler (BOSS)', sprite: 'restful-boss', hp: 130 }, question: 'Why does Rails prefer PATCH over PUT?', options: [{ id: 'a', text: 'PATCH is faster' }, { id: 'b', text: 'PUT replaces entire, PATCH updates partially' }, { id: 'c', text: 'PUT is deprecated' }, { id: 'd', text: 'Just convention' }], correct_answer: 'b', explanation: 'Semantically, PUT replaces entire resource, PATCH updates partially.' },

  // === ROUTING - NESTED (10) ===
  { id: 'routing-nested-001', type: 'code_analysis', difficulty: 2, xp_reward: 30, monster: { name: 'Nest Nibbler', sprite: 'nest-nibbler', hp: 60 }, question: 'What URL for comments index?', code_snippet: 'resources :articles do\n  resources :comments\nend', options: [{ id: 'a', text: '/comments' }, { id: 'b', text: '/articles/:article_id/comments' }, { id: 'c', text: '/articles/comments' }, { id: 'd', text: '/comments/:article_id' }], correct_answer: 'b', explanation: 'Nested resources include parent ID in URL.' },
  { id: 'routing-nested-002', type: 'fill_in_blank', difficulty: 2, xp_reward: 30, monster: { name: 'Parent Pest', sprite: 'parent-pest', hp: 60 }, question: 'In nested comments controller, article ID accessed via:', code_snippet: 'params[:____]', correct_answer: 'article_id', explanation: 'Nested params use singular_parent_id format.' },
  { id: 'routing-nested-003', type: 'multiple_choice', difficulty: 2, xp_reward: 35, monster: { name: 'Helper Harpy', sprite: 'helper-harpy', hp: 65 }, question: 'Path helper for nested comment?', options: [{ id: 'a', text: 'comment_path(@comment)' }, { id: 'b', text: 'article_comment_path(@article, @comment)' }, { id: 'c', text: 'nested_comment_path(@article, @comment)' }, { id: 'd', text: '@article.comments.path(@comment)' }], correct_answer: 'b', explanation: 'Nested helpers: parent_child_path(parent, child).' },
  { id: 'routing-nested-004', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Deep Dweller', sprite: 'deep-dweller', hp: 70 }, question: 'Why is nesting more than 1 level deep bad?', options: [{ id: 'a', text: 'Does not work' }, { id: 'b', text: 'URLs unwieldy, helpers complex' }, { id: 'c', text: 'Performance issues' }, { id: 'd', text: 'Actually fine' }], correct_answer: 'b', explanation: 'Deep nesting creates long URLs and complex helpers.' },
  { id: 'routing-nested-005', type: 'code_analysis', difficulty: 3, xp_reward: 40, monster: { name: 'Shallow Shade', sprite: 'shallow-shade', hp: 75 }, question: 'What routes does shallow: true NOT nest?', code_snippet: 'resources :articles do\n  resources :comments, shallow: true\nend', options: [{ id: 'a', text: 'index, new, create' }, { id: 'b', text: 'show, edit, update, destroy' }, { id: 'c', text: 'All become nested' }, { id: 'd', text: 'All become non-nested' }], correct_answer: 'b', explanation: 'shallow keeps index/new/create nested, un-nests show/edit/update/destroy.' },
  { id: 'routing-nested-006', type: 'fill_in_blank', difficulty: 3, xp_reward: 45, monster: { name: 'Scope Scorpion', sprite: 'scope-scorpion', hp: 75 }, question: 'Nest comments without full parent resources:', code_snippet: '____ "/articles/:article_id" do\n  resources :comments\nend', correct_answer: 'scope', explanation: 'scope adds URL prefix without full parent resource.' },
  { id: 'routing-nested-007', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Module Moth', sprite: 'module-moth', hp: 80 }, question: 'Does nesting affect which controller handles request?', options: [{ id: 'a', text: 'Uses ArticlesController for both' }, { id: 'b', text: 'Uses CommentsController' }, { id: 'c', text: 'Uses Articles::CommentsController' }, { id: 'd', text: 'Does not affect controller location' }], correct_answer: 'b', explanation: 'Nested resources still use standard controller by default.' },
  { id: 'routing-nested-008', type: 'code_analysis', difficulty: 4, xp_reward: 50, monster: { name: 'Concern Crawler', sprite: 'concern-crawler', hp: 85 }, question: 'What does this routing concern do?', code_snippet: 'concern :commentable do\n  resources :comments\nend\nresources :articles, concerns: :commentable\nresources :photos, concerns: :commentable', options: [{ id: 'a', text: 'Creates shared comment routes for both' }, { id: 'b', text: 'Makes comments belong to both models' }, { id: 'c', text: 'Creates polymorphic association' }, { id: 'd', text: 'Generates API docs' }], correct_answer: 'a', explanation: 'Concerns define reusable route blocks.' },
  { id: 'routing-nested-009', type: 'multiple_choice', difficulty: 4, xp_reward: 50, monster: { name: 'Form Phantom', sprite: 'form-phantom', hp: 85 }, question: 'In form for nested comment, what form_with URL?', code_snippet: '<%= form_with model: ??? do |f| %>', options: [{ id: 'a', text: 'model: @comment' }, { id: 'b', text: 'model: [@article, @comment]' }, { id: 'c', text: 'url: article_comments_path(@article)' }, { id: 'd', text: 'Both B and C work' }], correct_answer: 'd', explanation: 'model: [@article, @comment] is elegant, explicit url: also works.' },
  { id: 'routing-nested-010', type: 'multiple_choice', difficulty: 4, xp_reward: 55, monster: { name: 'Nested Nemesis (BOSS)', sprite: 'nested-boss', hp: 130 }, question: 'Best practice for nested resource URLs?', options: [{ id: 'a', text: 'Always nest to show relationships' }, { id: 'b', text: 'Never nest, use query params' }, { id: 'c', text: 'Nest only when parent ID needed to find resource' }, { id: 'd', text: 'Nest up to 3 levels' }], correct_answer: 'c', explanation: 'Nest when child is always accessed in parent context.' },

  // === ROUTING - CUSTOM (10) ===
  { id: 'routing-custom-001', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'GET Goblin', sprite: 'get-goblin', hp: 60 }, question: 'Create custom GET route to /about?', options: [{ id: 'a', text: 'get "/about", to: "pages#about"' }, { id: 'b', text: 'route :get, "/about"' }, { id: 'c', text: 'match "/about" => "pages#about"' }, { id: 'd', text: 'Both A and C work' }], correct_answer: 'd', explanation: 'Both work. get is more explicit.' },
  { id: 'routing-custom-002', type: 'fill_in_blank', difficulty: 2, xp_reward: 30, monster: { name: 'Named Nightmare', sprite: 'named-nightmare', hp: 60 }, question: 'Create named route helper for /about:', code_snippet: 'get "/about", to: "pages#about", ____: "about"', correct_answer: 'as', explanation: 'as: "about" creates about_path and about_url helpers.' },
  { id: 'routing-custom-003', type: 'multiple_choice', difficulty: 2, xp_reward: 35, monster: { name: 'Match Menace', sprite: 'match-menace', hp: 65 }, question: 'Why avoid "match" without specifying HTTP methods?', options: [{ id: 'a', text: 'Deprecated' }, { id: 'b', text: 'Matches all methods, security issue' }, { id: 'c', text: 'Does not work' }, { id: 'd', text: 'Slower' }], correct_answer: 'b', explanation: 'match without via: matches all HTTP methods - security risk.' },
  { id: 'routing-custom-004', type: 'code_analysis', difficulty: 3, xp_reward: 40, monster: { name: 'Redirect Revenant', sprite: 'redirect-revenant', hp: 70 }, question: 'What does this route do?', code_snippet: 'get "/old-path", to: redirect("/new-path")', options: [{ id: 'a', text: 'Returns 404' }, { id: 'b', text: 'Returns 301 redirect' }, { id: 'c', text: 'Renders new-path template' }, { id: 'd', text: 'Returns 302 redirect' }], correct_answer: 'b', explanation: 'redirect() returns 301 (permanent) by default.' },
  { id: 'routing-custom-005', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Wildcard Wraith', sprite: 'wildcard-wraith', hp: 75 }, question: 'What does asterisk capture?', code_snippet: 'get "/files/*path", to: "files#show"', options: [{ id: 'a', text: 'Only one segment' }, { id: 'b', text: 'All remaining segments as params[:path]' }, { id: 'c', text: 'Query parameters' }, { id: 'd', text: 'Invalid syntax' }], correct_answer: 'b', explanation: 'Wildcard captures everything: /files/a/b/c -> params[:path] = "a/b/c".' },
  { id: 'routing-custom-006', type: 'fill_in_blank', difficulty: 3, xp_reward: 45, monster: { name: 'Segment Specter', sprite: 'segment-specter', hp: 75 }, question: 'Capture dynamic username segment:', code_snippet: 'get "/:____", to: "profiles#show"', correct_answer: 'username', explanation: ':parameter captures that URL segment.' },
  { id: 'routing-custom-007', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Default Demon', sprite: 'default-demon', hp: 80 }, question: 'Set default value for optional segment?', options: [{ id: 'a', text: 'get "/posts(/:page)", defaults: { page: 1 }' }, { id: 'b', text: 'get "/posts/:page", page: 1' }, { id: 'c', text: 'get "/posts/:page = 1"' }, { id: 'd', text: 'get "/posts/:page", default_page: 1' }], correct_answer: 'a', explanation: 'Parentheses make optional, defaults: sets default values.' },
  { id: 'routing-custom-008', type: 'multiple_choice', difficulty: 4, xp_reward: 50, monster: { name: 'Root Raider', sprite: 'root-raider', hp: 85 }, question: 'Define different roots for different domains?', options: [{ id: 'a', text: 'root "home#index", domain: "example.com"' }, { id: 'b', text: 'Use constraints with request.domain' }, { id: 'c', text: 'Multiple root declarations' }, { id: 'd', text: 'Not possible' }], correct_answer: 'b', explanation: 'Use constraints to match domains.' },
  { id: 'routing-custom-009', type: 'code_analysis', difficulty: 4, xp_reward: 50, monster: { name: 'Direct Dragon', sprite: 'direct-dragon', hp: 85 }, question: 'What does this do?', code_snippet: 'direct :dashboard do\n  user_signed_in? ? user_dashboard_path : root_path\nend', options: [{ id: 'a', text: 'Creates conditional redirect' }, { id: 'b', text: 'Creates custom URL helper with dynamic logic' }, { id: 'c', text: 'Validates authentication' }, { id: 'd', text: 'Caches route' }], correct_answer: 'b', explanation: 'direct creates custom URL helpers with dynamic logic.' },
  { id: 'routing-custom-010', type: 'multiple_choice', difficulty: 4, xp_reward: 55, monster: { name: 'Custom Colossus (BOSS)', sprite: 'custom-boss', hp: 130 }, question: 'When use custom routes over resources?', options: [{ id: 'a', text: 'Always, more flexible' }, { id: 'b', text: 'For non-CRUD, static pages, special URLs' }, { id: 'c', text: 'Never, always use resources' }, { id: 'd', text: 'Only for APIs' }], correct_answer: 'b', explanation: 'Prefer resources for CRUD. Custom for static pages, special actions.' },

  // === ROUTING - CONSTRAINTS (10) ===
  { id: 'routing-constraints-001', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Regex Rat', sprite: 'regex-rat', hp: 60 }, question: 'What does this constraint do?', code_snippet: 'get "/users/:id", constraints: { id: /\\d+/ }', options: [{ id: 'a', text: 'Requires ID to be "d+"' }, { id: 'b', text: 'Requires ID to be one or more digits' }, { id: 'c', text: 'Makes ID optional' }, { id: 'd', text: 'Limits to 10 users' }], correct_answer: 'b', explanation: 'constraints: { id: /\\d+/ } requires digits only.' },
  { id: 'routing-constraints-002', type: 'fill_in_blank', difficulty: 2, xp_reward: 30, monster: { name: 'Format Fiend', sprite: 'format-fiend', hp: 60 }, question: 'Restrict route to JSON format only:', code_snippet: 'get "/api/users", ____: { format: "json" }', correct_answer: 'constraints', explanation: 'constraints restricts matching to specified format.' },
  { id: 'routing-constraints-003', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Subdomain Shade', sprite: 'subdomain-shade', hp: 70 }, question: 'Create routes only for "api" subdomain?', options: [{ id: 'a', text: 'namespace :api, subdomain: "api"' }, { id: 'b', text: 'constraints subdomain: "api" do ... end' }, { id: 'c', text: 'scope subdomain: "api" do ... end' }, { id: 'd', text: 'Both B and C work' }], correct_answer: 'd', explanation: 'Both constraints and scope can take subdomain:.' },
  { id: 'routing-constraints-004', type: 'code_analysis', difficulty: 3, xp_reward: 40, monster: { name: 'Class Creature', sprite: 'class-creature', hp: 75 }, question: 'What does this custom constraint do?', code_snippet: 'class AdminConstraint\n  def matches?(request)\n    request.session[:admin]\n  end\nend\nconstraints AdminConstraint.new do\n  resources :admin\nend', options: [{ id: 'a', text: 'Validates admin password' }, { id: 'b', text: 'Only matches if session[:admin] truthy' }, { id: 'c', text: 'Creates admin user' }, { id: 'd', text: 'Redirects non-admins' }], correct_answer: 'b', explanation: 'Custom constraint class must have matches?(request) method.' },
  { id: 'routing-constraints-005', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Lambda Lurker', sprite: 'lambda-lurker', hp: 75 }, question: 'Simpler way to write admin constraint?', options: [{ id: 'a', text: 'constraints: :admin' }, { id: 'b', text: 'constraints(-> (req) { req.session[:admin] }) { ... }' }, { id: 'c', text: 'if_admin { ... }' }, { id: 'd', text: 'guard :admin' }], correct_answer: 'b', explanation: 'Lambda constraints are concise for simple checks.' },
  { id: 'routing-constraints-006', type: 'fill_in_blank', difficulty: 3, xp_reward: 45, monster: { name: 'Host Haunt', sprite: 'host-haunt', hp: 80 }, question: 'Match only requests to specific host:', code_snippet: 'constraints ____: "www.example.com" do', correct_answer: 'host', explanation: 'host: matches the full host.' },
  { id: 'routing-constraints-007', type: 'multiple_choice', difficulty: 4, xp_reward: 50, monster: { name: 'IP Imp', sprite: 'ip-imp', hp: 85 }, question: 'Restrict routes to local network IPs?', options: [{ id: 'a', text: 'constraints: { ip: "192.168.*" }' }, { id: 'b', text: 'constraints(-> (r) { r.remote_ip.start_with?("192.168.") })' }, { id: 'c', text: 'local_only: true' }, { id: 'd', text: 'Not possible' }], correct_answer: 'b', explanation: 'Use lambda with request.remote_ip for IP constraints.' },
  { id: 'routing-constraints-008', type: 'multiple_choice', difficulty: 4, xp_reward: 50, monster: { name: 'Precedence Phantom', sprite: 'precedence-phantom', hp: 85 }, question: 'If two routes could match, which wins?', code_snippet: 'get "/users/:id"\nget "/users/new"', options: [{ id: 'a', text: 'More specific one (users/new)' }, { id: 'b', text: 'First one defined wins' }, { id: 'c', text: 'Raises error' }, { id: 'd', text: 'Both triggered' }], correct_answer: 'b', explanation: 'Rails matches top-to-bottom, first match wins. Reorder!' },
  { id: 'routing-constraints-009', type: 'code_analysis', difficulty: 4, xp_reward: 55, monster: { name: 'Request Reaper', sprite: 'request-reaper', hp: 90 }, question: 'What request properties can constraints access?', options: [{ id: 'a', text: 'Only URL parameters' }, { id: 'b', text: 'Full request: headers, session, cookies, IP, etc.' }, { id: 'c', text: 'Only subdomain and format' }, { id: 'd', text: 'Only HTTP method' }], correct_answer: 'b', explanation: 'Constraints receive full Rack request object.' },
  { id: 'routing-constraints-010', type: 'multiple_choice', difficulty: 4, xp_reward: 55, monster: { name: 'Constraint Champion (BOSS)', sprite: 'constraint-boss', hp: 130 }, question: 'Best use case for route constraints?', options: [{ id: 'a', text: 'User auth (prefer controller filters)' }, { id: 'b', text: 'Multi-tenancy, API versioning, subdomains' }, { id: 'c', text: 'Database queries (too slow)' }, { id: 'd', text: 'Form validation' }], correct_answer: 'b', explanation: 'Great for infrastructure routing. Keep auth in controllers.' },

  // === ROUTING - URL HELPERS (10) ===
  { id: 'routing-helpers-001', type: 'multiple_choice', difficulty: 2, xp_reward: 30, monster: { name: 'Path Pixie', sprite: 'path-pixie', hp: 60 }, question: 'Difference between article_path and article_url?', options: [{ id: 'a', text: 'Identical' }, { id: 'b', text: '_path returns relative, _url returns full URL with host' }, { id: 'c', text: '_url for external only' }, { id: 'd', text: '_path deprecated' }], correct_answer: 'b', explanation: '_path -> "/articles/1", _url -> "http://example.com/articles/1".' },
  { id: 'routing-helpers-002', type: 'fill_in_blank', difficulty: 2, xp_reward: 30, monster: { name: 'Plural Pest', sprite: 'plural-pest', hp: 60 }, question: 'For "resources :articles", index path helper is:', code_snippet: '____', correct_answer: 'articles_path', explanation: 'Plural for index, singular for show/edit/update/destroy.' },
  { id: 'routing-helpers-003', type: 'code_analysis', difficulty: 2, xp_reward: 35, monster: { name: 'Object Oracle', sprite: 'object-oracle', hp: 65 }, question: 'What does passing object to helper do?', code_snippet: 'link_to "Show", @article', options: [{ id: 'a', text: 'Uses @article.to_s as URL' }, { id: 'b', text: 'Rails infers article_path(@article)' }, { id: 'c', text: 'Renders article inline' }, { id: 'd', text: 'Raises error' }], correct_answer: 'b', explanation: 'Polymorphic routing infers correct path helper.' },
  { id: 'routing-helpers-004', type: 'multiple_choice', difficulty: 3, xp_reward: 40, monster: { name: 'Params Poltergeist', sprite: 'params-poltergeist', hp: 70 }, question: 'Add query parameters to path helper?', options: [{ id: 'a', text: 'articles_path + "?page=2"' }, { id: 'b', text: 'articles_path(page: 2)' }, { id: 'c', text: 'articles_path, params: { page: 2 }' }, { id: 'd', text: 'articles_path.query(page: 2)' }], correct_answer: 'b', explanation: 'Extra hash keys become query params.' },
  { id: 'routing-helpers-005', type: 'fill_in_blank', difficulty: 3, xp_reward: 40, monster: { name: 'Nested Nixie', sprite: 'nested-nixie', hp: 75 }, question: 'For nested comments, new comment path helper:', code_snippet: '____(@article)', correct_answer: 'new_article_comment_path', explanation: 'Nested helpers join names: new_parent_child_path.' },
  { id: 'routing-helpers-006', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Anchor Apparition', sprite: 'anchor-apparition', hp: 75 }, question: 'Add anchor to URL helper?', options: [{ id: 'a', text: 'article_path(@article) + "#comments"' }, { id: 'b', text: 'article_path(@article, anchor: "comments")' }, { id: 'c', text: 'article_path(@article, "#comments")' }, { id: 'd', text: 'article_path(@article).anchor("comments")' }], correct_answer: 'b', explanation: 'anchor: is special option for URL helpers.' },
  { id: 'routing-helpers-007', type: 'multiple_choice', difficulty: 3, xp_reward: 45, monster: { name: 'Format Phantom', sprite: 'format-phantom', hp: 80 }, question: 'Generate JSON URL?', code_snippet: 'article_path(@article, ???)', options: [{ id: 'a', text: 'type: :json' }, { id: 'b', text: 'format: :json' }, { id: 'c', text: 'as: :json' }, { id: 'd', text: 'ext: "json"' }], correct_answer: 'b', explanation: 'format: specifies extension: -> "/articles/1.json".' },
  { id: 'routing-helpers-008', type: 'code_analysis', difficulty: 4, xp_reward: 50, monster: { name: 'Polymorphic Phantom', sprite: 'poly-phantom', hp: 85 }, question: 'What does polymorphic_path do?', code_snippet: 'polymorphic_path([@article, @comment])', options: [{ id: 'a', text: 'Creates path for either articles or comments' }, { id: 'b', text: 'Creates article_comment_path(@article, @comment)' }, { id: 'c', text: 'Validates both are polymorphic' }, { id: 'd', text: 'Raises error' }], correct_answer: 'b', explanation: 'polymorphic_path infers correct helper from objects.' },
  { id: 'routing-helpers-009', type: 'multiple_choice', difficulty: 4, xp_reward: 50, monster: { name: 'Test Trickster', sprite: 'test-trickster', hp: 85 }, question: 'Use URL helpers in tests or outside views/controllers?', options: [{ id: 'a', text: 'Not available outside' }, { id: 'b', text: 'include Rails.application.routes.url_helpers' }, { id: 'c', text: 'Import from ActionController' }, { id: 'd', text: 'Use string URLs only' }], correct_answer: 'b', explanation: 'Include Rails.application.routes.url_helpers in any class.' },
  { id: 'routing-helpers-010', type: 'multiple_choice', difficulty: 4, xp_reward: 55, monster: { name: 'Helper Hero (BOSS)', sprite: 'helper-boss', hp: 130 }, question: 'Why prefer URL helpers over hardcoded strings?', options: [{ id: 'a', text: 'Faster' }, { id: 'b', text: 'If routes change, helpers still work; strings break' }, { id: 'c', text: 'Rails requires them' }, { id: 'd', text: 'They look nicer' }], correct_answer: 'b', explanation: 'URL helpers are route-aware. Change routes.rb and helpers auto-update.' },
];

// Build challenge map for quick lookups
const challenges: Map<string, Challenge> = new Map(
  allChallenges.map(c => [c.id, c])
);

export function getDungeonChallenges(dungeonId: string): Challenge[] {
  const prefix = dungeonToPrefix[dungeonId];
  if (!prefix) return [];
  return allChallenges.filter(c => c.id.startsWith(prefix));
}

export function getChallenge(challengeId: string): Challenge | undefined {
  return challenges.get(challengeId);
}

export function getAllChallenges(): Challenge[] {
  return allChallenges;
}

export function getDungeonMeta(dungeonId: string): { name: string; description: string } | undefined {
  return dungeonMeta[dungeonId];
}
